version: "3.9"
services:

  # nginx service
  nginx:
    container_name: "nginx"
    image: nginx:1.19.8-alpine
    depends_on:
      - mysite
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./conf.d:/etc/nginx/conf.d

  # application service
  mysite:
    container_name: "mysite"
    build: ./mysite
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 mysite.wsgi && celery -A mysite beat -l INFO"
    volumes:
      - ./mysite:/mysite
      - static_data:/project/static
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://django:django_QWErty!2)4@db:5432/django
      - DEBUG=1

  # database service
  db:
    image: postgres:13-alpine
    container_name: "postgres"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django_QWErty!2)4
      - POSTGRES_DB=django

  # pgbouncer service
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: "pgbouncer"
    environment:
      - DB_USER=django
      - DB_PASSWORD=django_QWErty!2)4
      - DB_HOST=db
      - DB_NAME=django
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,dbuser
    ports:
      - "5432:5432"
    depends_on:
      - db

  # celery service
  celery:
    container_name: "celery"
    build: ./mysite
    command: celery -A mysite worker -l INFO
    volumes:
      - ./mysite:/mysite
    environment:
      - DATABASE_URL=postgresql://django:django_QWErty!2)4@db:5432/django
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - mysite
      - redis

  # redis service
  redis:
    container_name: "redis"
    image: "redis:alpine"

volumes:
  pg_data:
  static_data:
